name: Replace a container of api-gateway-service
hosts: all
become: false
tasks:
  - name: Stop a container
    community.docker.docker_container:
      name: api-gateway-service
      state: stopped

  - name: Remove container
    community.docker.docker_container:
      name: api-gateway-service
      state: absent

  - name: Remove image
    community.docker.docker_image:
      state: absent
      name: splendidpdf/api-gateway-service
      tag: 0.0.1-SNAPSHOT

  - name: Run api gateway service
    community.docker.docker_container:
      name: api-gateway-service
      image: splendidpdf/api-gateway-service:0.0.1-SNAPSHOT
      state: started
      pull: true
      ports:
        - "7777:7777"
      env:
        SPRING_CONFIG_IMPORT: "configserver:http://51.250.102.12:8888"
        SPRING_CLOUD_CONFIG_LABEL: "develop"