- name: Replace a container of review-service
  hosts: all
  become: false
  tasks:
     - name: Get infos on 'review-service' container
      docker_container_info:
        name: review-service
      register: result

    - name: Does container exist?
      debug:
        msg: "The container {{ 'exists' if result.exists else 'does not exist' }}"
  
    - name: Stop a container
      community.docker.docker_container:
        name: review-service
        state: stopped
      when: result.exists

    - name: Remove container
      community.docker.docker_container:
        name: review-service
        state: absent
      when: result.exists

    - name: Remove image
      community.docker.docker_image:
        state: absent
        name: splendidpdf/review-service
        tag: 0.0.1-SNAPSHOT
      when: result.exists

    - name: Run review service
      community.docker.docker_container:
        name: review-service
        image: splendidpdf/review-service:0.0.1-SNAPSHOT
        state: started
        pull: true
        ports:
          - "8082:8082"
        env:
          SPRING_CONFIG_IMPORT: "configserver:http://51.250.102.12:8888"
          SPRING_CLOUD_CONFIG_LABEL: "develop"
